### ISSUE TITLE
high availability and load balancing

### ISSUE THREAD

**Issue by rock1103** [petkivim/xrd4j#14]
Hi:
xrd4j  supports xroad security server high availability? if these is multiple security servers, how do I configure in code,now the xrd4j   demo only one security server url in the code.
I also discuss with xroad author,here is https://github.com/vrk-kpa/xroad-public/issues/23
thank you.

**Comment by rock1103** [comment]
thank you, I think this way to implement load balanced is simple. Can I use Nginx/LVS/HAProxy  to configure multiple security server,and XRd4J can use one url to call xroad?

**Comment by petkivim** [comment]
Yes, you're right, this implementation is very simple and not fail safe. You can use Nginx/LVS/HAProxy between XRd4J client and multiple security servers. In that case the XRd4J client calls the load balancer which takes care of distributing the requests between security servers in your cluster.
