### ISSUE TITLE
Moving xrd4j repository to vrk-kpa Github repository?

### ISSUE THREAD

**Issue by hanhaka** [petkivim/xrd4j#16]
Hi,

as agreed earlier, we would like to move the xrd4j repository to be a part of vrk-kpa Github repository (https://github.com/vrk-kpa/). The new repository would still be public and open for everyone to contribute.

We are now pretty close to start the process for moving the repository due to there is some needs for further development of xrd4j library.
Do you mind if we start the moving operation soon?

Regards,
Hannu

**Comment by petkivim** [comment]
Hi,

Moving the repository is OK for me so feel free to proceed with the relocation process. Please let me know when the repository has been moved.

Thanks,
Petteri

**Comment by hanhaka** [comment]
Great, thanks!

We let you know when the new repository is created. Hopefully is will be realized very soon but summer vacations might delay it a little bit.

Regards,
Hannu

**Comment by iluwatar** [comment]
@petkivim @hanhaka the repository has now been moved to https://github.com/vrk-kpa/xrd4j

**Comment by petkivim** [comment]
@iluwatar Thanks for the info. Good job! :)
