### ISSUE TITLE
Closing xrd4j repository?

### ISSUE THREAD

**Issue by hanhaka** [petkivim/xrd4j#17]
Hi,

Could you close down the xrd4j repository (or change it to be an Private Repository)?

We have cloned/moved the existing xrd4j repository (this repository) to under VRK's Github account to here: https://github.com/vrk-kpa/xrd4j

Currently it confuses Finnish X-Road users and developers as there are two existing repositories for pretty much same purpose.

Thanks,
Hannu
Suomi.fi-palveluväylä (X-Road) Product Owner

**Comment by petkivim** [comment]
Added a note in the repository's description and README.md that this repository is no longer maintained and a link to the new repository. However, this repository will be kept for archive purposes.
