### ISSUE TITLE
ee.ria.xroad.common.message

### ISSUE THREAD

**Issue by kakoni** [petkivim/xrd4j#5]
Noticed that in xroad 6 packages there is a common library that seems to include various utility classes for handling soap messages/requests (for example ee.ria.xroad.common.message, ee.ria.xroad.common.request). 

- Are there any similarities between xrd4j and that ee.ria.xroad.common package? 
- Anyidea is that ee.ria.xroad.common source/documentation available somewhere?

**Comment by petkivim** [comment]
XRd4J is completely independent library and it doesn't have a shared code base with ee.ria.xroad.common package. On functional level they probably have same functionalities, but I haven't taken a closer look at ee.ria.xroad.common package, so I can't say how many functional similarities there are.

As far as I know ee.ria.xroad.common source/documentation is not currently publicly available.

**Comment by petkivim** [comment]
X-Road common library can be found here:

https://github.com/vrk-kpa/xroad-public/tree/master/src/common-util/src/main/java/ee/ria/xroad/common
